server:
  port : 0
  
spring:
  application:
    name: ms_auth_service
#  cloud:
#    config:
#      enabled: true
#      uri: http://localhost:8081
jwt:
  secret: secret
  
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    hostname: localhost