server:
  port: 8086
spring:
  application:
    name: ms-sba-server
  security:
    user:
      name: admin
      password: admin

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    hostname: localhost