server:
  port: 8090
  
spring:
  application:
    name: ms-api-gateway
    zipking: http://localhost:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - AuthFilter
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8086
        username: ${SBA_SERVER_USERNAME:admin}
        password: ${SBA_SERVER_PASSWORD:admin}
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
     
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    hostname: localhost
    

    
