server:
  port: 8090
  
spring:
  application:
    name: ms_api_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms_prueba_seguridad
          uri: lb://ms_prueba_seguridad
          predicates:
            - Path=/prueba/**
          filters:
            - AuthFilter
        - id: ms_auth_service
          uri: lb://ms_auth_service
          predicates:
            - Path=/auth/**    
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    hostname: localhost
    

    