server:
  port : 0

spring:
  application:
    name: user-service
    zipking: http://localhost:9411
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8086
        username: ${SBA_SERVER_USERNAME:admin}
        password: ${SBA_SERVER_PASSWORD:admin}
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: 77810931
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SYSTEM
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always      

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    hostname: localhost
