server:
  port : 0

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: 77810931
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SYSTEM
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    hostname: localhost
