server:
  port : ${PORT:${SERVER_PORT:0}}
  
spring:
  application:
    name: ms-auth-service

jwt:
  secret: secret

admin-paths:
  paths:
    -
      uri: "/user/list"
      method: "GET"
    -
      uri: "/user/{1}[1-9]+[0-9]*"
      method: "GET"
    -
      uri:  "/user/createUser"
      method: "POST"
    -
      uri: "/user/deleteUser/{1}[1-9]+[0-9]*"
      method: "DELETE"

#    -
#      uri: "/useri/savecar/{1}[1-9]+[0-9]*"
#      method: "POST"
  
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    hostname: localhost