spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe  # Utilizando el Service Name
    username: C##ORACLE
    password: 77810931
  jpa:
    hibernate:
      ddl-auto: update  # Hibernate se encargará de la creación/actualización del esquema
    show-sql: true  # Mostrar las consultas SQL generadas